[book]
title = "Ignitix Documentation"
authors = ["caniko"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
site-url = "/ignitix/docs/"
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/caniko/ignitix"

